### ISSUE TITLE
Pre-release build 12.10 for Mac does not start...

### ISSUE THREAD

**Issue by tobkle** [SouthbankSoftware/dbkoda#2] opened 2017-10-14 13:21 UTC
https://github.com/SouthbankSoftware/dbkoda/releases/download/12-10-2017/dbKoda-0.8.0-beta.1.12-10-2017.dmg

Only shows start screen with moving logo, but doesn't get to main screen

**Comment by guiguan** [comment] 2017-10-16 03:16
Hi, @tobkle 

Can you check to see whether you have a JRE (Java runtime) installed for your macOS? We have recently added a beta feature that requires a JRE to be installed. If not, the app will fail to start. If you have JRE installed, and you still get this error, are you using JRE 1.9?

In the upcoming release version, we will remove that requirement.

**Comment by RipleyLudicrous1979** [comment] 2017-12-08 16:36
I assume the JRE installation requirement is still in place? I'm running JRE 9.0.1+11 and still getting the error modal when starting up DBKoda.

**Comment by guiguan** [comment] 2017-12-12 02:16
@RipleyLudicrous1979 We have removed Java as a dependency requirement in latest nightly builds. Have you tried the latest one?

**Comment by guiguan** [comment] 2017-12-19 22:20
@cmoetzing thanks for reporting this. The behavior you have described is really weird, and we couldn't reproduce it on our Ubuntu systems (same version). Could you please provide us those logs files? https://dbkoda.useresponse.com/knowledge-base/article/where-are-the-dbkoda-log-files

**Comment by cmoetzing** [comment] 2017-12-19 22:30
Nothing interesting there.
```
2017-12-19T21:18:14+01:00 - notice: Starting up with Production mode...
2017-12-19T21:18:14+01:00 - info:   Controller process PID: 27602
2017-12-19T21:18:38+01:00 - notice: Shutting down...
```
Now that I managed to start if via extracted deb I retried the AppImage and now that works too.
What I did with my first try:

1. download file
2. move it to /opt (with sudo)
3. make executable (with sudo)
4. start with `/opt/dbkoda.appimage` (without sudo)
5. closed it and tried again, didn't work either

**Comment by cmoetzing** [comment] 2017-12-20 14:16
I can reproduce the issue with a fresh VM:

1. install ubuntu 17.10 (package selection "Ubuntu desktop")
2. download AppImage
3. move to /opt
4. make executable
5. start with normal user privileges
6. the log in `~/.config/dbkoda/logs` stays the same
```
2017-12-20T14:57:08+01:00 - ^[[32mnotice^[[39m: ^[[32mStarting up with Production mode...^[[39m
2017-12-20T14:57:08+01:00 - ^[[30minfo^[[39m: ^[[30m  Controller process PID: 2939^[[39m
```
the console gives following output
```
user@ubuntu:~$ /opt/dbkoda-latest.AppImage 
2017-12-20T14:57:08+01:00 - notice: Starting up with Production mode...
2017-12-20T14:57:08+01:00 - info:   Controller process PID: 2939
/tmp/.mount_OOwaP9/usr/bin/@southbanksoftwaredbkoda: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
Error:
controller exited with error, please check logs at https://goo.gl/fGcFmv and report this issue
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
```
The application is stuck with the spinning logo. I can open the about dialog and close it correctly. All other menu controls do not work.

**Comment by guiguan** [comment] 2017-12-20 23:13
@cmoetzing it looks like that `libgconf` is a requirement after Chrome 42 on linux. Can you try `apt-get install libgconf-2-4` (https://github.com/electron/electron/issues/1518)?

**Comment by cmoetzing** [comment] 2017-12-21 01:16
Yep that fixes it. I don't really get why a Chrome dependency is necessary outside the AppImage. Isn't the image supposed to bring all dependencies?

**Comment by guiguan** [comment] 2017-12-21 01:51
Yes, a bit weird. I guess that they have decided that `libgconf` (https://packages.debian.org/sid/libgconf-2-4) should be more of a shared and built-in system lib.

**Closed** 2018-01-12 00:23 UTC
